### PR TITLE
Adding mvc20-pepe logo

### PR DESCRIPTION
**Pull request by N0fear92**
Dear dev,

We like to add our mvc20-pepe logo on mvcscan.com

### CODE REVIEW

**Comment by N0fear92** [comment]
Dear lgs18828191781,

I hope this message finds you well. Firstly, I want to extend my gratitude for your efforts in setting up our logo.

The Pepe community has one additional request: could you kindly relocate our token to the first page alongside MSP, MC, and other tokens? We believe this adjustment would be beneficial.

Looking forward to your response.

Kind regards,
N0fear92

**Comment by lgs18928191781** [comment]
We have received your pull request from your end. The merge operation has been performed, and could you please check if it has taken effect?


尜∵生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mvc-labs/icons.mvcscan.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 下午2:00
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [mvc-labs/icons.mvcscan.com] Adding mvc20-pepe logo (PR #2)





 
Dear lgs18828191781,
 
I hope this message finds you well. Firstly, I want to extend my gratitude for your efforts in setting up our logo.
 
The Pepe community has one additional request: could you kindly relocate our token to the first page alongside MSP, MC, and other tokens? We believe this adjustment would be beneficial.
 
Looking forward to your response.
 
Kind regards,
 N0fear92

**Comment by N0fear92** [comment]
It has taken effect sir. 

Thank you.

**Comment by N0fear92** [comment]
Could you please consider my other request as well. That would be great. 

Thank you

Looking forward to hearing from you.

**Comment by lgs18928191781** [comment]
Sure, you can inform me via email or contact me using Telegram. My Telegram username is @esaon_leung. You can search for it at&nbsp;https://t.me/esaon_leung.


尜∵生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mvc-labs/icons.mvcscan.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 下午2:10
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [mvc-labs/icons.mvcscan.com] Adding mvc20-pepe logo (PR #2)





 
Could you please consider my other request as well. That would be great.
 
Thank you
 
Looking forward to hearing from you.

**Pull request merged**
